services:
  - type: web
    name: screen-connect-server
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 --timeout 300 --keep-alive 75 --bind 0.0.0.0:$PORT server:app
    envVars:
      - key: LOG_FILE
        value: stdout
      - key: CRASH_DIR
        value: /tmp/crashes
